export type CategoryDefinition = {
  id: string;
  label: string;
  words: string[];
};

// Each category's words should be unique across the whole pool -- the
// selection logic in categoriesCore.ts skips any day where the 3 chosen
// categories would share a word, so overlap here just shrinks how many
// valid combinations exist. Kept intentionally common/well-known (see the
// crossword's "obscure geography" lesson): every word here should be
// recognizable to a casual player, not a specialist.
export const CATEGORY_POOL: CategoryDefinition[] = [
  { id: "primary-colors", label: "Colors", words: ["RED", "BLUE", "YELLOW", "GREEN"] },
  { id: "big-cats", label: "Big Cats", words: ["LION", "TIGER", "LEOPARD", "CHEETAH"] },
  { id: "chess-pieces", label: "Chess Pieces", words: ["KING", "QUEEN", "BISHOP", "KNIGHT"] },
  { id: "planets", label: "Planets", words: ["MARS", "VENUS", "SATURN", "NEPTUNE"] },
  { id: "ice-cream-flavors", label: "Ice Cream Flavors", words: ["VANILLA", "CHOCOLATE", "STRAWBERRY", "PISTACHIO"] },
  { id: "card-games", label: "Card Games", words: ["POKER", "RUMMY", "SOLITAIRE", "CANASTA"] },
  { id: "dance-styles", label: "Dance Styles", words: ["BALLET", "TANGO", "SALSA", "WALTZ"] },
  { id: "orchestra-instruments", label: "Orchestra Instruments", words: ["TRUMPET", "CLARINET", "CELLO", "OBOE"] },
  { id: "board-games", label: "Board Games", words: ["MONOPOLY", "SCRABBLE", "CLUEDO", "RISK"] },
  { id: "gems", label: "Gemstones", words: ["DIAMOND", "EMERALD", "RUBY", "SAPPHIRE"] },
  { id: "kitchen-appliances", label: "Kitchen Appliances", words: ["TOASTER", "BLENDER", "KETTLE", "MICROWAVE"] },
  { id: "superheroes", label: "Superheroes", words: ["BATMAN", "SUPERMAN", "SPIDERMAN", "IRONMAN"] },
  { id: "weather-events", label: "Weather Events", words: ["STORM", "BLIZZARD", "HURRICANE", "DROUGHT"] },
  { id: "dog-breeds", label: "Dog Breeds", words: ["POODLE", "BEAGLE", "HUSKY", "BOXER"] },
  { id: "citrus-fruits", label: "Citrus Fruits", words: ["LEMON", "LIME", "ORANGE", "TANGERINE"] },
  { id: "pasta-shapes", label: "Pasta Shapes", words: ["SPAGHETTI", "PENNE", "RAVIOLI", "LASAGNA"] },
  { id: "olympic-sports", label: "Olympic Sports", words: ["SWIMMING", "GYMNASTICS", "ARCHERY", "FENCING"] },
  { id: "shakespeare-plays", label: "Shakespeare Plays", words: ["HAMLET", "MACBETH", "OTHELLO", "TEMPEST"] },
  { id: "norse-gods", label: "Norse Gods", words: ["ODIN", "THOR", "LOKI", "FREYA"] },
  { id: "greek-gods", label: "Greek Gods", words: ["ZEUS", "APOLLO", "HERMES", "ATHENA"] },
  { id: "us-presidents", label: "US Presidents", words: ["LINCOLN", "WASHINGTON", "JEFFERSON", "MADISON"] },
  { id: "car-brands", label: "Car Brands", words: ["TOYOTA", "HONDA", "FERRARI", "MAZDA"] },
  { id: "cocktails", label: "Cocktails", words: ["MOJITO", "MARTINI", "MARGARITA", "DAIQUIRI"] },
  { id: "breads", label: "Types of Bread", words: ["BAGUETTE", "CIABATTA", "BRIOCHE", "PRETZEL"] },
  { id: "ocean-creatures", label: "Ocean Creatures", words: ["DOLPHIN", "OCTOPUS", "JELLYFISH", "STARFISH"] },
  { id: "birds-of-prey", label: "Birds of Prey", words: ["EAGLE", "FALCON", "HAWK", "OWL"] },
  { id: "yoga-poses", label: "Yoga Poses", words: ["WARRIOR", "COBRA", "LOTUS", "BRIDGE"] },
  { id: "cloud-types", label: "Cloud Types", words: ["CUMULUS", "CIRRUS", "STRATUS", "NIMBUS"] },
  { id: "string-instruments", label: "String Instruments", words: ["VIOLIN", "VIOLA", "HARP", "BANJO"] },
  { id: "pizza-toppings", label: "Pizza Toppings", words: ["PEPPERONI", "MUSHROOM", "OLIVE", "BACON"] },
  { id: "martial-arts", label: "Martial Arts", words: ["KARATE", "JUDO", "TAEKWONDO", "AIKIDO"] },
  { id: "spices", label: "Spices", words: ["CINNAMON", "NUTMEG", "PAPRIKA", "TURMERIC"] },
  { id: "constellations", label: "Constellations", words: ["ORION", "GEMINI", "LEO", "TAURUS"] },
  { id: "zodiac-signs", label: "Zodiac Signs", words: ["ARIES", "LIBRA", "SCORPIO", "PISCES"] },
  { id: "fairy-tale-characters", label: "Fairy Tale Characters", words: ["CINDERELLA", "RAPUNZEL", "PINOCCHIO", "ALADDIN"] },
  { id: "board-sports", label: "Board Sports", words: ["SURFING", "SKATING", "SNOWBOARDING", "WAKEBOARDING"] },
  { id: "herbs", label: "Herbs", words: ["BASIL", "THYME", "OREGANO", "ROSEMARY"] },
  { id: "shades-of-blue", label: "Shades of Blue", words: ["NAVY", "TEAL", "COBALT", "AZURE"] },
  { id: "shades-of-red", label: "Shades of Red", words: ["CRIMSON", "SCARLET", "MAROON", "BURGUNDY"] },
  { id: "dinosaurs", label: "Dinosaurs", words: ["TRICERATOPS", "STEGOSAURUS", "VELOCIRAPTOR", "BRONTOSAURUS"] },
  { id: "teas", label: "Types of Tea", words: ["MATCHA", "OOLONG", "CHAMOMILE", "ROOIBOS"] },
  { id: "ice-cream-toppings", label: "Ice Cream Toppings", words: ["SPRINKLES", "FUDGE", "CARAMEL", "MARSHMALLOW"] },
  { id: "farm-animals", label: "Farm Animals", words: ["COW", "PIG", "SHEEP", "GOAT"] },
  { id: "insects", label: "Insects", words: ["ANT", "BEE", "WASP", "BEETLE"] },
  { id: "reptiles", label: "Reptiles", words: ["SNAKE", "LIZARD", "IGUANA", "GECKO"] },
  { id: "amphibians", label: "Amphibians", words: ["FROG", "TOAD", "NEWT", "SALAMANDER"] },
  { id: "primates", label: "Primates", words: ["GORILLA", "CHIMPANZEE", "ORANGUTAN", "BABOON"] },
  { id: "marsupials", label: "Marsupials", words: ["KANGAROO", "KOALA", "WOMBAT", "WALLABY"] },
  { id: "types-of-hats", label: "Types of Hats", words: ["FEDORA", "BERET", "SOMBRERO", "BEANIE"] },
  { id: "shoe-types", label: "Types of Shoes", words: ["SNEAKER", "SANDAL", "LOAFER", "BOOT"] },
  { id: "punctuation-marks", label: "Punctuation Marks", words: ["COMMA", "PERIOD", "SEMICOLON", "APOSTROPHE"] },
  { id: "currencies", label: "World Currencies", words: ["DOLLAR", "EURO", "PESO", "YEN"] },
  { id: "desserts", label: "Desserts", words: ["TIRAMISU", "BROWNIE", "CHEESECAKE", "MACARON"] },
  { id: "sandwiches", label: "Sandwiches", words: ["REUBEN", "PANINI", "BLT", "GYRO"] },
  { id: "breakfast-foods", label: "Breakfast Foods", words: ["PANCAKE", "WAFFLE", "OMELET", "BAGEL"] },
  { id: "salad-greens", label: "Salad Greens", words: ["LETTUCE", "SPINACH", "ARUGULA", "KALE"] },
  { id: "root-vegetables", label: "Root Vegetables", words: ["CARROT", "POTATO", "BEET", "TURNIP"] },
  { id: "nuts", label: "Nuts", words: ["ALMOND", "CASHEW", "WALNUT", "PECAN"] },
  { id: "card-suits", label: "Card Suits", words: ["HEARTS", "SPADES", "CLUBS", "DIAMONDS"] },
  { id: "sports-balls", label: "Ball Sports", words: ["BASKETBALL", "FOOTBALL", "VOLLEYBALL", "SOFTBALL"] },
  { id: "house-pets", label: "House Pets", words: ["DOG", "CAT", "HAMSTER", "PARROT"] },
  { id: "shades-of-purple", label: "Shades of Purple", words: ["LAVENDER", "VIOLET", "LILAC", "PLUM"] },
  { id: "tools", label: "Tools", words: ["HAMMER", "WRENCH", "SCREWDRIVER", "PLIERS"] },
  { id: "movie-genres", label: "Movie Genres", words: ["COMEDY", "HORROR", "THRILLER", "ROMANCE"] },
  { id: "music-genres", label: "Music Genres", words: ["JAZZ", "ROCK", "REGGAE", "TECHNO"] },
  { id: "continents", label: "Continents", words: ["AFRICA", "ASIA", "EUROPE", "ANTARCTICA"] },
  { id: "seasons", label: "Seasons", words: ["SPRING", "SUMMER", "AUTUMN", "WINTER"] },
  { id: "fictional-wizards", label: "Fictional Wizards", words: ["GANDALF", "DUMBLEDORE", "MERLIN", "SAURON"] },
  { id: "pirate-words", label: "Pirate Words", words: ["TREASURE", "CUTLASS", "PLANK", "COMPASS"] },
  { id: "pixar-movies", label: "Pixar Movies", words: ["COCO", "BRAVE", "ONWARD", "LUCA"] },
  { id: "berries", label: "Berries", words: ["BLUEBERRY", "RASPBERRY", "BLACKBERRY", "CRANBERRY"] },
  { id: "shapes", label: "Shapes", words: ["TRIANGLE", "HEXAGON", "PENTAGON", "OCTAGON"] },
  { id: "keyboard-instruments", label: "Keyboard Instruments", words: ["PIANO", "ORGAN", "HARPSICHORD", "ACCORDION"] },
  { id: "cheese-types", label: "Types of Cheese", words: ["CHEDDAR", "BRIE", "GOUDA", "FETA"] },
  { id: "space-objects", label: "Space Objects", words: ["COMET", "ASTEROID", "METEOR", "NEBULA"] },
  { id: "party-games", label: "Party Games", words: ["CHARADES", "PICTIONARY", "TWISTER", "JENGA"] },
  { id: "garden-tools", label: "Garden Tools", words: ["SHOVEL", "RAKE", "TROWEL", "PRUNER"] },
];
